name: exploring Workflow Dispatch Trigger
on:
  workflow_dispatch:
    inputs:
      run-job:
        description: "Run specific Job"
        type: boolean
        required: false
      custom_message:
        description: "Enter a custom message"
        type: string
        required: true
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      -run: echo "Exploring Workflow Dispatch Trigger"
